import type { DailyTheftMetrics } from '../logic/dailyTheftMetrics'
import type { ReportDef } from '../types'

/**
 * The 12th full report. Two of its sections are COMPUTED from live hierarchy
 * data (see logic/dailyTheftMetrics.ts), so the def is produced by a builder
 * rather than stored as a frozen constant. Everything else is static, extracted
 * verbatim from the prototype.
 */
export function buildDailyTheftReport(m: DailyTheftMetrics): ReportDef {
  return {
    ...{
      "title": "Daily Theft Summary · 06 May 2026",
      "subtitle": "AI-narrated overnight detection · auto-distributed 07:00 IST",
      "docNo": "UPPCL/AI/DAILY-THEFT/06-MAY-2026",
      "classification": "Internal · for CMD + Directors + 5 SE",
      "regulator": "Auto-generated",
      "legalCite": "Internal report · not for external distribution",
      "footer": "Auto-generated by VidyutRaksha at 07:00 IST. Distributed to CMD, 3 Directors, 5 SEs by email + push. Drill-down via web app or mobile."
    },
    sections: [
      {
        heading: "1. Headline Metrics · Overnight (22:00 05 May — 06:00 06 May IST)",
        blocks: [
          {
            kind: 'metricGrid',
            cols: 4,
            tiles: [
              { label: 'New criticals', value: `+${m.newCriticals}`, sub: 'flagged overnight', tone: 'red' },
              {
                label: 'Closed yesterday',
                value: String(m.closedYesterday),
                sub: `cases · ${m.recoveredDisp} recovered`,
                tone: 'green',
              },
              { label: 'Avg risk score', value: '0.82', sub: 'of overnight cohort' },
              {
                label: 'Confidence ≥ 90%',
                value: String(m.confHighCount),
                sub: `of ${m.newCriticals} (66%)`,
                tone: 'purple',
              },
            ],
          },
          { kind: 'caption', html: "<strong style=\"color:var(--ai-purple)\">✦ AI narrative:</strong> Overnight detection volume 23% above 30-day rolling avg. Likely driver: pre-monsoon load surge unmasking dormant tamper events. Highest concentration in DVVNL Agra zone (38% of new criticals)." },
        ],
      },
      {
        heading: "2. Top Critical Cases · By Assessment Value",
        blocks: [
          {
            "kind": "table",
            "cols": [
              {
                "label": "Case ID"
              },
              {
                "label": "Consumer"
              },
              {
                "label": "DT · zone"
              },
              {
                "label": "Estimated theft",
                "align": "right"
              },
              {
                "label": "Risk",
                "align": "right"
              }
            ],
            "rows": [
              {
                "cells": [
                  {
                    "text": "C-20260506-001",
                    "mono": true,
                    "fontSize": "10px"
                  },
                  {
                    "text": "Bharat Steel & Wire Co",
                    "bold": true
                  },
                  {
                    "text": "DTR-1849 · Kamachha",
                    "color": "var(--text-mid)",
                    "fontSize": "10px"
                  },
                  {
                    "text": "₹14.8L",
                    "align": "right",
                    "mono": true,
                    "bold": true,
                    "color": "var(--red)"
                  },
                  {
                    "text": "0.96",
                    "align": "right",
                    "mono": true,
                    "color": "var(--ai-purple)"
                  }
                ]
              },
              {
                "cells": [
                  {
                    "text": "C-20260506-008",
                    "mono": true,
                    "fontSize": "10px"
                  },
                  {
                    "text": "Sharma Bros Mills",
                    "bold": true
                  },
                  {
                    "text": "DTR-2247 · Trans-Yamuna",
                    "color": "var(--text-mid)",
                    "fontSize": "10px"
                  },
                  {
                    "text": "₹9.4L",
                    "align": "right",
                    "mono": true,
                    "bold": true,
                    "color": "var(--red)"
                  },
                  {
                    "text": "0.93",
                    "align": "right",
                    "mono": true,
                    "color": "var(--ai-purple)"
                  }
                ]
              },
              {
                "cells": [
                  {
                    "text": "C-20260506-012",
                    "mono": true,
                    "fontSize": "10px"
                  },
                  {
                    "text": "Annapurna Atta Chakki",
                    "bold": true
                  },
                  {
                    "text": "DTR-1942 · Bhelupur",
                    "color": "var(--text-mid)",
                    "fontSize": "10px"
                  },
                  {
                    "text": "₹6.2L",
                    "align": "right",
                    "mono": true,
                    "bold": true,
                    "color": "var(--red)"
                  },
                  {
                    "text": "0.91",
                    "align": "right",
                    "mono": true,
                    "color": "var(--ai-purple)"
                  }
                ]
              },
              {
                "cells": [
                  {
                    "text": "C-20260506-019",
                    "mono": true,
                    "fontSize": "10px"
                  },
                  {
                    "text": "Kashi Cold Storage",
                    "bold": true
                  },
                  {
                    "text": "DTR-3120 · Sigra",
                    "color": "var(--text-mid)",
                    "fontSize": "10px"
                  },
                  {
                    "text": "₹5.8L",
                    "align": "right",
                    "mono": true,
                    "bold": true,
                    "color": "var(--red)"
                  },
                  {
                    "text": "0.89",
                    "align": "right",
                    "mono": true,
                    "color": "var(--ai-purple)"
                  }
                ]
              },
              {
                "cells": [
                  {
                    "text": "C-20260506-024",
                    "mono": true,
                    "fontSize": "10px"
                  },
                  {
                    "text": "Singh Manufacturing",
                    "bold": true
                  },
                  {
                    "text": "DTR-1748 · Naini",
                    "color": "var(--text-mid)",
                    "fontSize": "10px"
                  },
                  {
                    "text": "₹4.6L",
                    "align": "right",
                    "mono": true,
                    "bold": true,
                    "color": "var(--red)"
                  },
                  {
                    "text": "0.88",
                    "align": "right",
                    "mono": true,
                    "color": "var(--ai-purple)"
                  }
                ]
              }
            ]
          },
          {
            kind: 'caption',
            html: `Top 5 of ${m.newCriticals} new criticals. Full list available via "Open queue" button. Estimated aggregate exposure (${m.newCriticals} cases): ₹${m.aggExposureCr} Cr.`,
          },
        ],
      },
      ...([
      {
        "heading": "3. Cluster Detections",
        "blocks": [
          {
            "kind": "table",
            "cols": [],
            "rows": [
              {
                "cells": [
                  {
                    "text": "Aliganj area · simultaneous load drop pattern",
                    "width": "50%"
                  },
                  {
                    "text": "18 meters · pattern detected 04:18 IST · possible organised",
                    "color": "var(--text-mid)",
                    "fontSize": "10.5px"
                  },
                  {
                    "text": "",
                    "width": "30px"
                  }
                ]
              },
              {
                "cells": [
                  {
                    "text": "Sigra · comms-offline cluster",
                    "width": "50%"
                  },
                  {
                    "text": "23 meters silent > 48h · AMISP SLA breach + possible tamper",
                    "color": "var(--text-mid)",
                    "fontSize": "10.5px"
                  },
                  {
                    "text": "",
                    "width": "30px"
                  }
                ]
              },
              {
                "cells": [
                  {
                    "text": "Bhelupur · phase-imbalance cluster",
                    "width": "50%"
                  },
                  {
                    "text": "12 DTs with phase imbalance > 25% · could indicate hooking on R/Y/B phases",
                    "color": "var(--text-mid)",
                    "fontSize": "10.5px"
                  },
                  {
                    "text": "",
                    "width": "30px"
                  }
                ]
              },
              {
                "cells": [
                  {
                    "text": "Kamachha · repeat-offender geographic concentration",
                    "width": "50%"
                  },
                  {
                    "text": "7 prior confirmed-theft consumers within 200m radius · network effect risk",
                    "color": "var(--text-mid)",
                    "fontSize": "10.5px"
                  },
                  {
                    "text": "",
                    "width": "30px"
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        "heading": "4. Field Assignment Summary",
        "blocks": [
          {
            "kind": "table",
            "cols": [],
            "rows": [
              {
                "cells": [
                  {
                    "text": "Inspections scheduled today",
                    "color": "var(--text-mid)",
                    "width": "48%"
                  },
                  {
                    "text": "42 across 5 DISCOMs",
                    "bold": true
                  }
                ]
              },
              {
                "cells": [
                  {
                    "text": "High-priority (assessed > ₹5L)",
                    "color": "var(--text-mid)",
                    "width": "48%"
                  },
                  {
                    "text": "18 routed to senior inspectors",
                    "bold": true
                  }
                ]
              },
              {
                "cells": [
                  {
                    "text": "Cluster-driven inspections",
                    "color": "var(--text-mid)",
                    "width": "48%"
                  },
                  {
                    "text": "14 (Aliganj + Sigra + Bhelupur + Kamachha)",
                    "bold": true
                  }
                ]
              },
              {
                "cells": [
                  {
                    "text": "Standard random inspections",
                    "color": "var(--text-mid)",
                    "width": "48%"
                  },
                  {
                    "text": "10 (per inspector daily target)",
                    "bold": true
                  }
                ]
              },
              {
                "cells": [
                  {
                    "text": "Inspector roster availability",
                    "color": "var(--text-mid)",
                    "width": "48%"
                  },
                  {
                    "text": "47 of 52 (5 on leave / training)",
                    "bold": true
                  }
                ]
              },
              {
                "cells": [
                  {
                    "text": "Avg inspections per inspector",
                    "color": "var(--text-mid)",
                    "width": "48%"
                  },
                  {
                    "text": "0.9 (target: 1.5/day)",
                    "bold": true
                  }
                ]
              }
            ]
          }
        ]
      },
      {
        "heading": "5. Recovery Trend · Last 7 Days",
        "blocks": [
          {
            "kind": "table",
            "cols": [
              {
                "label": "Date"
              },
              {
                "label": "Cases closed",
                "align": "right"
              },
              {
                "label": "Recovered",
                "align": "right"
              },
              {
                "label": "Hit rate",
                "align": "right"
              }
            ],
            "rows": [
              {
                "cells": [
                  {
                    "text": "30 Apr (Wed)"
                  },
                  {
                    "text": "14",
                    "align": "right",
                    "mono": true
                  },
                  {
                    "text": "₹38L",
                    "align": "right",
                    "mono": true,
                    "color": "var(--green)"
                  },
                  {
                    "text": "58%",
                    "align": "right",
                    "mono": true
                  }
                ]
              },
              {
                "cells": [
                  {
                    "text": "01 May (Thu)"
                  },
                  {
                    "text": "17",
                    "align": "right",
                    "mono": true
                  },
                  {
                    "text": "₹52L",
                    "align": "right",
                    "mono": true,
                    "color": "var(--green)"
                  },
                  {
                    "text": "61%",
                    "align": "right",
                    "mono": true
                  }
                ]
              },
              {
                "cells": [
                  {
                    "text": "02 May (Fri)"
                  },
                  {
                    "text": "21",
                    "align": "right",
                    "mono": true
                  },
                  {
                    "text": "₹64L",
                    "align": "right",
                    "mono": true,
                    "color": "var(--green)"
                  },
                  {
                    "text": "63%",
                    "align": "right",
                    "mono": true
                  }
                ]
              },
              {
                "cells": [
                  {
                    "text": "03 May (Sat)"
                  },
                  {
                    "text": "11",
                    "align": "right",
                    "mono": true
                  },
                  {
                    "text": "₹28L",
                    "align": "right",
                    "mono": true,
                    "color": "var(--green)"
                  },
                  {
                    "text": "55%",
                    "align": "right",
                    "mono": true
                  }
                ]
              },
              {
                "cells": [
                  {
                    "text": "04 May (Sun)"
                  },
                  {
                    "text": "8",
                    "align": "right",
                    "mono": true
                  },
                  {
                    "text": "₹22L",
                    "align": "right",
                    "mono": true,
                    "color": "var(--green)"
                  },
                  {
                    "text": "50%",
                    "align": "right",
                    "mono": true
                  }
                ]
              },
              {
                "cells": [
                  {
                    "text": "05 May (Mon)"
                  },
                  {
                    "text": "18",
                    "align": "right",
                    "mono": true
                  },
                  {
                    "text": "₹47L",
                    "align": "right",
                    "mono": true,
                    "color": "var(--green)"
                  },
                  {
                    "text": "57%",
                    "align": "right",
                    "mono": true
                  }
                ]
              },
              {
                "cells": [
                  {
                    "text": "7-day total"
                  },
                  {
                    "text": "107",
                    "align": "right",
                    "mono": true
                  },
                  {
                    "text": "₹284L",
                    "align": "right",
                    "mono": true,
                    "color": "var(--green)"
                  },
                  {
                    "text": "58% avg",
                    "align": "right",
                    "mono": true
                  }
                ],
                "variant": "green"
              }
            ]
          }
        ]
      }
    ] as ReportDef['sections']),
    ],
  }
}
